/*
 * Copyright (c) 2021-2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// 缩略图获取尺寸
export enum ThumbnailSize {
  WIDTH = 98,
  HEIGHT = 98
}

export enum ZIndex {
  TOP = 999,
  MIDDLE = 99,
  LOW = 9,
  LEVEL10 = 10,
  LEVEL100 = 100,
  LEVEL101 = 101
}

export const TREE_LAYER = 15

export enum BottomBarColor {
  enabled = 1,
  disabled = 0.3
}

export enum SystemBarColor {
  WHITE = '#ffffff',
  BLACK = '#000000',
  LIGHT_GRAY = '#f0f1f6'
}