/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2022. All rights reserved.
 */

/**
 * [常量]<BR>
 *
 * @author
 * @version [V1.0.0.0, 2021/12/28]
 * @since V1.0.0.0
 */
export class Constants {
  /**
   * Bundle name of audioPicker
   */
  static readonly AUDIO_PICKER_BUNDLE = 'com.ohos.filepicker';

  /**
   * AudioPicker每页请求数量
   */
  static readonly PICKER_PAGE_SIZE: number = 100

  /**
   * 每次请求参数
   */
  static readonly PAGE_COUNT: number = 1

  // AUDIO PICKER
  static readonly AUDIO_PICKER_PAGE_TYPE:string = 'aodioPickerMusic'
}