/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2022. All rights reserved.
 */

/**
 * [常量]<BR>
 *
 */
export class Constants {
  /**
   * Bundle name of audioPicker
   */
  public static readonly AUDIO_PICKER_BUNDLE = 'com.ohos.filepicker';

  /**
   * AudioPicker每页请求数量
   */
  public static readonly PICKER_PAGE_SIZE: number = 100

  /**
   * 每次请求参数
   */
  public static readonly PAGE_COUNT: number = 1
}